# Generated by Django 6.1.1 on 2026-09-03 06:32

import django.db.models.deletion
import django.utils.timezone
import tutor.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spanish', models.CharField(max_length=200)),
                ('english', models.CharField(max_length=200)),
                ('topic', models.CharField(choices=[('daily_routine', 'Daily Routine'), ('ordering_food', 'Ordering Food'), ('travel_basics', 'Travel Basics')], db_index=True, max_length=32)),
                ('part_of_speech', models.CharField(blank=True, max_length=32)),
                ('example_es', models.CharField(blank=True, max_length=300)),
                ('example_en', models.CharField(blank=True, max_length=300)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['topic', 'difficulty', 'spanish'],
                'constraints': [models.UniqueConstraint(fields=('topic', 'spanish'), name='uniq_vocabitem_topic_spanish')],
            },
        ),
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('daily_routine', 'Daily Routine'), ('ordering_food', 'Ordering Food'), ('travel_basics', 'Travel Basics')], max_length=32)),
                ('turn_limit', models.PositiveSmallIntegerField(default=tutor.models.default_turn_limit)),
                ('is_complete', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
                ('target_items', models.ManyToManyField(blank=True, related_name='sessions', to='tutor.vocabitem')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserVocabState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval_days', models.PositiveIntegerField(default=0)),
                ('due_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('last_quality', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('correct_reviews', models.PositiveIntegerField(default=0)),
                ('lapses', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_states', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='tutor.vocabitem')),
            ],
            options={
                'ordering': ['due_date', 'item__spanish'],
                'constraints': [models.UniqueConstraint(fields=('user', 'item'), name='uniq_uservocabstate_user_item')],
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('tutor_message_es', models.TextField()),
                ('tutor_message_en', models.TextField(blank=True)),
                ('suggested_replies', models.JSONField(blank=True, default=list)),
                ('user_reply', models.TextField(blank=True)),
                ('reply_mode', models.CharField(blank=True, choices=[('chip', 'Suggested reply (chip)'), ('freetext', 'Free text')], max_length=16)),
                ('was_correct', models.BooleanField(blank=True, null=True)),
                ('sm2_quality', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('feedback_en', models.TextField(blank=True)),
                ('corrected_es', models.CharField(blank=True, max_length=300)),
                ('llm_provider', models.CharField(blank=True, max_length=32)),
                ('from_cache', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='tutor.conversationsession')),
                ('target_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turns', to='tutor.vocabitem')),
            ],
            options={
                'ordering': ['session', 'index'],
                'constraints': [models.UniqueConstraint(fields=('session', 'index'), name='uniq_turn_session_index')],
            },
        ),
    ]
