# Generated by Django 6.1.1 on 2026-09-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsession',
            name='planned_item_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
