# Generated by Django 6.1.1 on 2026-09-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_conversationsession_planned_item_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservocabstate',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
