# Generated by Django 6.1.1 on 2026-09-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_uservocabstate_is_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='sentence_starter',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
