"""Seed the three practice topics with vocabulary, and create the demo learner.

Idempotent: re-running updates existing rows rather than duplicating them, so
it is safe to run after every deploy.

    python manage.py seed_vocab
    python manage.py seed_vocab --reset   # wipe vocab and scheduling state first
"""

from django.conf import settings
from django.contrib.auth.models import User
from django.core.management.base import BaseCommand
from django.db import transaction

from tutor.models import (
    DAILY_ROUTINE,
    ORDERING_FOOD,
    TRAVEL_BASICS,
    ConversationSession,
    UserVocabState,
    VocabItem,
)

# (term, english, part_of_speech, example, example_en, difficulty)
# Hindi adds a seventh value: the romanisation.
SPANISH_VOCAB = {
    DAILY_ROUTINE: [
        ('despertarse', 'to wake up', 'verb',
         'Me despierto a las siete.', 'I wake up at seven.', 1),
        ('levantarse', 'to get up', 'verb',
         'Me levanto temprano.', 'I get up early.', 1),
        ('desayunar', 'to have breakfast', 'verb',
         'Desayuno pan y café.', 'I have bread and coffee for breakfast.', 1),
        ('ducharse', 'to shower', 'verb',
         'Me ducho por la mañana.', 'I shower in the morning.', 1),
        ('vestirse', 'to get dressed', 'verb',
         'Me visto rápido.', 'I get dressed quickly.', 2),
        ('cepillarse los dientes', "to brush one's teeth", 'phrase',
         'Me cepillo los dientes.', 'I brush my teeth.', 2),
        ('el trabajo', 'work, job', 'noun',
         'Voy al trabajo en autobús.', 'I go to work by bus.', 1),
        ('almorzar', 'to have lunch', 'verb',
         'Almuerzo a la una.', 'I have lunch at one.', 1),
        ('cenar', 'to have dinner', 'verb',
         'Cenamos a las ocho.', 'We have dinner at eight.', 1),
        ('acostarse', 'to go to bed', 'verb',
         'Me acuesto a las once.', 'I go to bed at eleven.', 2),
        ('la mañana', 'morning', 'noun',
         'Por la mañana leo.', 'In the morning I read.', 1),
        ('la tarde', 'afternoon', 'noun',
         'Estudio por la tarde.', 'I study in the afternoon.', 1),
        ('la noche', 'night', 'noun',
         'Trabajo por la noche.', 'I work at night.', 1),
        ('temprano', 'early', 'adverb',
         'Me levanto muy temprano.', 'I get up very early.', 1),
        ('tarde', 'late', 'adverb',
         'Llego tarde al trabajo.', 'I arrive late to work.', 2),
        ('siempre', 'always', 'adverb',
         'Siempre desayuno en casa.', 'I always have breakfast at home.', 1),
        ('a veces', 'sometimes', 'phrase',
         'A veces corro por la mañana.', 'Sometimes I run in the morning.', 2),
        ('antes de', 'before', 'preposition',
         'Antes de dormir leo un libro.', 'Before sleeping I read a book.', 2),
        ('después de', 'after', 'preposition',
         'Después de cenar veo la tele.', 'After dinner I watch TV.', 2),
        ('descansar', 'to rest', 'verb',
         'Descanso el domingo.', 'I rest on Sunday.', 1),
    ],
    ORDERING_FOOD: [
        ('la mesa', 'table', 'noun',
         'Una mesa para dos, por favor.', 'A table for two, please.', 1),
        ('el menú', 'menu', 'noun',
         '¿Me trae el menú?', 'Could you bring me the menu?', 1),
        ('el camarero', 'waiter', 'noun',
         'El camarero es muy amable.', 'The waiter is very kind.', 1),
        ('pedir', 'to order', 'verb',
         'Quiero pedir la paella.', 'I want to order the paella.', 2),
        ('la cuenta', 'the bill, the check', 'noun',
         'La cuenta, por favor.', 'The bill, please.', 1),
        ('el agua', 'water', 'noun',
         'Un vaso de agua, por favor.', 'A glass of water, please.', 1),
        ('el vino', 'wine', 'noun',
         'Una copa de vino tinto.', 'A glass of red wine.', 1),
        ('el pan', 'bread', 'noun',
         '¿Nos trae más pan?', 'Could you bring us more bread?', 1),
        ('el plato', 'dish, plate', 'noun',
         'Este plato está delicioso.', 'This dish is delicious.', 1),
        ('la bebida', 'drink', 'noun',
         '¿Qué bebida quiere?', 'What would you like to drink?', 1),
        ('el postre', 'dessert', 'noun',
         'De postre, un flan.', 'For dessert, a flan.', 2),
        ('la ensalada', 'salad', 'noun',
         'Una ensalada mixta, por favor.', 'A mixed salad, please.', 1),
        ('el pollo', 'chicken', 'noun',
         'Pollo con arroz.', 'Chicken with rice.', 1),
        ('la carne', 'meat', 'noun',
         'No como carne.', "I don't eat meat.", 1),
        ('el pescado', 'fish', 'noun',
         'El pescado está muy fresco.', 'The fish is very fresh.', 1),
        ('picante', 'spicy', 'adjective',
         '¿Es muy picante?', 'Is it very spicy?', 2),
        ('para llevar', 'to take away', 'phrase',
         'Es para llevar.', "It's to take away.", 2),
        ('quisiera', 'I would like', 'phrase',
         'Quisiera un café, por favor.', 'I would like a coffee, please.', 2),
        ('¿cuánto cuesta?', 'how much does it cost?', 'phrase',
         '¿Cuánto cuesta el menú del día?', 'How much is the set menu?', 2),
        ('soy alérgico a', "I'm allergic to", 'phrase',
         'Soy alérgico a los frutos secos.', "I'm allergic to nuts.", 3),
    ],
    TRAVEL_BASICS: [
        ('el aeropuerto', 'airport', 'noun',
         'Voy al aeropuerto en taxi.', "I'm going to the airport by taxi.", 1),
        ('el billete', 'ticket', 'noun',
         'Un billete a Madrid, por favor.', 'A ticket to Madrid, please.', 1),
        ('la estación', 'station', 'noun',
         'La estación está cerca.', 'The station is close by.', 1),
        ('el tren', 'train', 'noun',
         'El tren sale a las nueve.', 'The train leaves at nine.', 1),
        ('el autobús', 'bus', 'noun',
         'Tomo el autobús al centro.', 'I take the bus downtown.', 1),
        ('el hotel', 'hotel', 'noun',
         'El hotel está en el centro.', 'The hotel is downtown.', 1),
        ('la habitación', 'room', 'noun',
         'Una habitación doble, por favor.', 'A double room, please.', 2),
        ('la maleta', 'suitcase', 'noun',
         'Mi maleta es azul.', 'My suitcase is blue.', 1),
        ('el pasaporte', 'passport', 'noun',
         'Aquí está mi pasaporte.', 'Here is my passport.', 1),
        ('¿dónde está?', 'where is?', 'phrase',
         '¿Dónde está el baño?', 'Where is the bathroom?', 1),
        ('a la derecha', 'to the right', 'phrase',
         'Gire a la derecha.', 'Turn right.', 2),
        ('a la izquierda', 'to the left', 'phrase',
         'El museo está a la izquierda.', 'The museum is on the left.', 2),
        ('cerca', 'near', 'adverb',
         'La playa está cerca.', 'The beach is near.', 1),
        ('lejos', 'far', 'adverb',
         'El aeropuerto está lejos.', 'The airport is far.', 1),
        ('perdido', 'lost', 'adjective',
         'Estoy perdido.', "I'm lost.", 2),
        ('el mapa', 'map', 'noun',
         '¿Tiene un mapa de la ciudad?', 'Do you have a map of the city?', 1),
        ('reservar', 'to book, to reserve', 'verb',
         'Quiero reservar una habitación.', 'I want to book a room.', 2),
        ('el vuelo', 'flight', 'noun',
         'Mi vuelo se retrasó.', 'My flight was delayed.', 2),
        ('¿a qué hora sale?', 'what time does it leave?', 'phrase',
         '¿A qué hora sale el tren?', 'What time does the train leave?', 2),
        ('la ayuda', 'help', 'noun',
         'Necesito ayuda, por favor.', 'I need help, please.', 1),
    ],
}


FRENCH_VOCAB = {
    DAILY_ROUTINE: [
        ('se réveiller', 'to wake up', 'verb',
         'Je me réveille à sept heures.', 'I wake up at seven.', 1),
        ('se lever', 'to get up', 'verb',
         'Je me lève tôt.', 'I get up early.', 1),
        ('prendre le petit déjeuner', 'to have breakfast', 'phrase',
         'Je prends du pain et du café.', 'I have bread and coffee.', 1),
        ('se doucher', 'to shower', 'verb',
         'Je me douche le matin.', 'I shower in the morning.', 1),
        ("s'habiller", 'to get dressed', 'verb',
         "Je m'habille vite.", 'I get dressed quickly.', 2),
        ('se brosser les dents', "to brush one's teeth", 'phrase',
         'Je me brosse les dents.', 'I brush my teeth.', 2),
        ('le travail', 'work, job', 'noun',
         'Je vais au travail en bus.', 'I go to work by bus.', 1),
        ('déjeuner', 'to have lunch', 'verb',
         'Je déjeune à une heure.', 'I have lunch at one.', 1),
        ('dîner', 'to have dinner', 'verb',
         'Nous dînons à huit heures.', 'We have dinner at eight.', 1),
        ('se coucher', 'to go to bed', 'verb',
         'Je me couche à onze heures.', 'I go to bed at eleven.', 2),
        ('le matin', 'morning', 'noun',
         'Le matin je lis.', 'In the morning I read.', 1),
        ("l'après-midi", 'afternoon', 'noun',
         "J'étudie l'après-midi.", 'I study in the afternoon.', 1),
        ('le soir', 'evening', 'noun',
         'Je travaille le soir.', 'I work in the evening.', 1),
        ('tôt', 'early', 'adverb',
         'Je me lève très tôt.', 'I get up very early.', 1),
        ('tard', 'late', 'adverb',
         "J'arrive tard au travail.", 'I arrive late to work.', 2),
        ('toujours', 'always', 'adverb',
         'Je prends toujours le petit déjeuner.', 'I always have breakfast.', 1),
        ('parfois', 'sometimes', 'adverb',
         'Parfois je cours le matin.', 'Sometimes I run in the morning.', 2),
        ('avant de', 'before', 'preposition',
         'Avant de dormir je lis.', 'Before sleeping I read.', 2),
        ('après', 'after', 'preposition',
         'Après le dîner je regarde la télé.', 'After dinner I watch TV.', 2),
        ('se reposer', 'to rest', 'verb',
         'Je me repose le dimanche.', 'I rest on Sunday.', 1),
    ],
    ORDERING_FOOD: [
        ('la table', 'table', 'noun',
         "Une table pour deux, s'il vous plaît.", 'A table for two, please.', 1),
        ('le menu', 'menu', 'noun',
         "Vous pouvez m'apporter le menu ?", 'Could you bring me the menu?', 1),
        ('le serveur', 'waiter', 'noun',
         'Le serveur est très gentil.', 'The waiter is very kind.', 1),
        ('commander', 'to order', 'verb',
         'Je veux commander le poulet.', 'I want to order the chicken.', 2),
        ("l'addition", 'the bill, the check', 'noun',
         "L'addition, s'il vous plaît.", 'The bill, please.', 1),
        ("l'eau", 'water', 'noun',
         "Un verre d'eau, s'il vous plaît.", 'A glass of water, please.', 1),
        ('le vin', 'wine', 'noun',
         'Un verre de vin rouge.', 'A glass of red wine.', 1),
        ('le pain', 'bread', 'noun',
         'Vous pouvez apporter plus de pain ?', 'Could you bring more bread?', 1),
        ('le plat', 'dish', 'noun',
         'Ce plat est délicieux.', 'This dish is delicious.', 1),
        ('la boisson', 'drink', 'noun',
         'Quelle boisson voulez-vous ?', 'What would you like to drink?', 1),
        ('le dessert', 'dessert', 'noun',
         'Comme dessert, une crème brûlée.', 'For dessert, a creme brulee.', 2),
        ('la salade', 'salad', 'noun',
         "Une salade mixte, s'il vous plaît.", 'A mixed salad, please.', 1),
        ('le poulet', 'chicken', 'noun',
         'Du poulet avec du riz.', 'Chicken with rice.', 1),
        ('la viande', 'meat', 'noun',
         'Je ne mange pas de viande.', "I don't eat meat.", 1),
        ('le poisson', 'fish', 'noun',
         'Le poisson est très frais.', 'The fish is very fresh.', 1),
        ('épicé', 'spicy', 'adjective',
         "C'est très épicé ?", 'Is it very spicy?', 2),
        ('à emporter', 'to take away', 'phrase',
         "C'est à emporter.", "It's to take away.", 2),
        ('je voudrais', 'I would like', 'phrase',
         "Je voudrais un café, s'il vous plaît.", 'I would like a coffee, please.', 2),
        ('combien ça coûte', 'how much does it cost', 'phrase',
         'Combien coûte le menu du jour ?', 'How much is the set menu?', 2),
        ('je suis allergique à', "I'm allergic to", 'phrase',
         'Je suis allergique aux noix.', "I'm allergic to nuts.", 3),
    ],
    TRAVEL_BASICS: [
        ("l'aéroport", 'airport', 'noun',
         "Je vais à l'aéroport en taxi.", "I'm going to the airport by taxi.", 1),
        ('le billet', 'ticket', 'noun',
         "Un billet pour Paris, s'il vous plaît.", 'A ticket to Paris, please.', 1),
        ('la gare', 'station', 'noun',
         'La gare est tout près.', 'The station is very close.', 1),
        ('le train', 'train', 'noun',
         'Le train part à neuf heures.', 'The train leaves at nine.', 1),
        ('le bus', 'bus', 'noun',
         'Je prends le bus pour le centre.', 'I take the bus downtown.', 1),
        ("l'hôtel", 'hotel', 'noun',
         "L'hôtel est dans le centre.", 'The hotel is downtown.', 1),
        ('la chambre', 'room', 'noun',
         "Une chambre double, s'il vous plaît.", 'A double room, please.', 2),
        ('la valise', 'suitcase', 'noun',
         'Ma valise est bleue.', 'My suitcase is blue.', 1),
        ('le passeport', 'passport', 'noun',
         'Voici mon passeport.', 'Here is my passport.', 1),
        ('où est', 'where is', 'phrase',
         'Où sont les toilettes ?', 'Where is the bathroom?', 1),
        ('à droite', 'to the right', 'phrase',
         'Tournez à droite.', 'Turn right.', 2),
        ('à gauche', 'to the left', 'phrase',
         'Le musée est à gauche.', 'The museum is on the left.', 2),
        ('près', 'near', 'adverb',
         "La plage est près d'ici.", 'The beach is near here.', 1),
        ('loin', 'far', 'adverb',
         "L'aéroport est loin.", 'The airport is far.', 1),
        ('perdu', 'lost', 'adjective',
         'Je suis perdu.', "I'm lost.", 2),
        ('le plan', 'map', 'noun',
         'Vous avez un plan de la ville ?', 'Do you have a map of the city?', 1),
        ('réserver', 'to book, to reserve', 'verb',
         'Je veux réserver une chambre.', 'I want to book a room.', 2),
        ('le vol', 'flight', 'noun',
         'Mon vol a du retard.', 'My flight is delayed.', 2),
        ('à quelle heure part', 'what time does it leave', 'phrase',
         'À quelle heure part le train ?', 'What time does the train leave?', 2),
        ("l'aide", 'help', 'noun',
         "J'ai besoin d'aide, s'il vous plaît.", 'I need help, please.', 1),
    ],
}


GERMAN_VOCAB = {
    DAILY_ROUTINE: [
        ('aufwachen', 'to wake up', 'verb',
         'Ich wache um sieben Uhr auf.', 'I wake up at seven.', 1),
        ('aufstehen', 'to get up', 'verb',
         'Ich stehe früh auf.', 'I get up early.', 1),
        ('frühstücken', 'to have breakfast', 'verb',
         'Ich frühstücke Brot und Kaffee.', 'I have bread and coffee for breakfast.', 1),
        ('duschen', 'to shower', 'verb',
         'Ich dusche am Morgen.', 'I shower in the morning.', 1),
        ('sich anziehen', 'to get dressed', 'verb',
         'Ich ziehe mich schnell an.', 'I get dressed quickly.', 2),
        ('sich die Zähne putzen', "to brush one's teeth", 'phrase',
         'Ich putze mir die Zähne.', 'I brush my teeth.', 2),
        ('die Arbeit', 'work, job', 'noun',
         'Ich fahre mit dem Bus zur Arbeit.', 'I go to work by bus.', 1),
        ('zu Mittag essen', 'to have lunch', 'phrase',
         'Ich esse um eins zu Mittag.', 'I have lunch at one.', 1),
        ('zu Abend essen', 'to have dinner', 'phrase',
         'Wir essen um acht zu Abend.', 'We have dinner at eight.', 1),
        ('ins Bett gehen', 'to go to bed', 'phrase',
         'Ich gehe um elf ins Bett.', 'I go to bed at eleven.', 2),
        ('der Morgen', 'morning', 'noun',
         'Am Morgen lese ich.', 'In the morning I read.', 1),
        ('der Nachmittag', 'afternoon', 'noun',
         'Ich lerne am Nachmittag.', 'I study in the afternoon.', 1),
        ('die Nacht', 'night', 'noun',
         'Ich arbeite in der Nacht.', 'I work at night.', 1),
        ('früh', 'early', 'adverb',
         'Ich stehe sehr früh auf.', 'I get up very early.', 1),
        ('spät', 'late', 'adverb',
         'Ich komme spät zur Arbeit.', 'I arrive late to work.', 2),
        ('immer', 'always', 'adverb',
         'Ich frühstücke immer zu Hause.', 'I always have breakfast at home.', 1),
        ('manchmal', 'sometimes', 'adverb',
         'Manchmal laufe ich am Morgen.', 'Sometimes I run in the morning.', 2),
        ('vor', 'before', 'preposition',
         'Vor dem Schlafen lese ich.', 'Before sleeping I read.', 2),
        ('nach', 'after', 'preposition',
         'Nach dem Abendessen sehe ich fern.', 'After dinner I watch TV.', 2),
        ('sich ausruhen', 'to rest', 'verb',
         'Ich ruhe mich am Sonntag aus.', 'I rest on Sunday.', 1),
    ],
    ORDERING_FOOD: [
        ('der Tisch', 'table', 'noun',
         'Einen Tisch für zwei, bitte.', 'A table for two, please.', 1),
        ('die Speisekarte', 'menu', 'noun',
         'Bringen Sie mir bitte die Speisekarte.', 'Please bring me the menu.', 1),
        ('der Kellner', 'waiter', 'noun',
         'Der Kellner ist sehr nett.', 'The waiter is very kind.', 1),
        ('bestellen', 'to order', 'verb',
         'Ich möchte das Schnitzel bestellen.', 'I want to order the schnitzel.', 2),
        ('die Rechnung', 'the bill, the check', 'noun',
         'Die Rechnung, bitte.', 'The bill, please.', 1),
        ('das Wasser', 'water', 'noun',
         'Ein Glas Wasser, bitte.', 'A glass of water, please.', 1),
        ('der Wein', 'wine', 'noun',
         'Ein Glas Rotwein.', 'A glass of red wine.', 1),
        ('das Brot', 'bread', 'noun',
         'Bringen Sie uns mehr Brot?', 'Could you bring us more bread?', 1),
        ('das Gericht', 'dish', 'noun',
         'Dieses Gericht ist lecker.', 'This dish is delicious.', 1),
        ('das Getränk', 'drink', 'noun',
         'Welches Getränk möchten Sie?', 'What would you like to drink?', 1),
        ('der Nachtisch', 'dessert', 'noun',
         'Als Nachtisch einen Kuchen.', 'A cake for dessert.', 2),
        ('der Salat', 'salad', 'noun',
         'Einen gemischten Salat, bitte.', 'A mixed salad, please.', 1),
        ('das Hähnchen', 'chicken', 'noun',
         'Hähnchen mit Reis.', 'Chicken with rice.', 1),
        ('das Fleisch', 'meat', 'noun',
         'Ich esse kein Fleisch.', "I don't eat meat.", 1),
        ('der Fisch', 'fish', 'noun',
         'Der Fisch ist sehr frisch.', 'The fish is very fresh.', 1),
        ('scharf', 'spicy', 'adjective',
         'Ist das sehr scharf?', 'Is it very spicy?', 2),
        ('zum Mitnehmen', 'to take away', 'phrase',
         'Das ist zum Mitnehmen.', "It's to take away.", 2),
        ('ich hätte gern', 'I would like', 'phrase',
         'Ich hätte gern einen Kaffee.', 'I would like a coffee.', 2),
        ('was kostet das', 'how much does it cost', 'phrase',
         'Was kostet das Tagesmenü?', 'How much is the set menu?', 2),
        ('ich bin allergisch gegen', "I'm allergic to", 'phrase',
         'Ich bin allergisch gegen Nüsse.', "I'm allergic to nuts.", 3),
    ],
    TRAVEL_BASICS: [
        ('der Flughafen', 'airport', 'noun',
         'Ich fahre mit dem Taxi zum Flughafen.', "I'm going to the airport by taxi.", 1),
        ('die Fahrkarte', 'ticket', 'noun',
         'Eine Fahrkarte nach Berlin, bitte.', 'A ticket to Berlin, please.', 1),
        ('der Bahnhof', 'station', 'noun',
         'Der Bahnhof ist in der Nähe.', 'The station is close by.', 1),
        ('der Zug', 'train', 'noun',
         'Der Zug fährt um neun Uhr.', 'The train leaves at nine.', 1),
        ('der Bus', 'bus', 'noun',
         'Ich nehme den Bus ins Zentrum.', 'I take the bus downtown.', 1),
        ('das Hotel', 'hotel', 'noun',
         'Das Hotel ist im Zentrum.', 'The hotel is downtown.', 1),
        ('das Zimmer', 'room', 'noun',
         'Ein Doppelzimmer, bitte.', 'A double room, please.', 2),
        ('der Koffer', 'suitcase', 'noun',
         'Mein Koffer ist blau.', 'My suitcase is blue.', 1),
        ('der Reisepass', 'passport', 'noun',
         'Hier ist mein Reisepass.', 'Here is my passport.', 1),
        ('wo ist', 'where is', 'phrase',
         'Wo ist die Toilette?', 'Where is the bathroom?', 1),
        ('nach rechts', 'to the right', 'phrase',
         'Gehen Sie nach rechts.', 'Turn right.', 2),
        ('nach links', 'to the left', 'phrase',
         'Das Museum ist nach links.', 'The museum is on the left.', 2),
        ('in der Nähe', 'near', 'phrase',
         'Der Strand ist in der Nähe.', 'The beach is near.', 1),
        ('weit', 'far', 'adverb',
         'Der Flughafen ist weit.', 'The airport is far.', 1),
        ('verirrt', 'lost', 'adjective',
         'Ich habe mich verirrt.', "I'm lost.", 2),
        ('die Karte', 'map', 'noun',
         'Haben Sie eine Karte der Stadt?', 'Do you have a map of the city?', 1),
        ('reservieren', 'to book, to reserve', 'verb',
         'Ich möchte ein Zimmer reservieren.', 'I want to book a room.', 2),
        ('der Flug', 'flight', 'noun',
         'Mein Flug hat Verspätung.', 'My flight is delayed.', 2),
        ('wann fährt er ab', 'what time does it leave', 'phrase',
         'Wann fährt der Zug ab?', 'What time does the train leave?', 2),
        ('die Hilfe', 'help', 'noun',
         'Ich brauche Hilfe, bitte.', 'I need help, please.', 1),
    ],
}


# Seven values, not six: Devanagari is unreadable to an English beginner, so
# each term carries how it sounds.
HINDI_VOCAB = {
    DAILY_ROUTINE: [
        ('जागना', 'to wake up', 'verb',
         'मैं सात बजे जागता हूँ।', 'I wake up at seven.', 1, 'jaagna'),
        ('उठना', 'to get up', 'verb',
         'मैं जल्दी उठता हूँ।', 'I get up early.', 1, 'uthna'),
        ('नाश्ता करना', 'to have breakfast', 'phrase',
         'मैं रोटी और चाय का नाश्ता करता हूँ।',
         'I have bread and tea for breakfast.', 1, 'naashta karna'),
        ('नहाना', 'to shower, to bathe', 'verb',
         'मैं सुबह नहाता हूँ।', 'I shower in the morning.', 1, 'nahaana'),
        ('कपड़े पहनना', 'to get dressed', 'phrase',
         'मैं जल्दी कपड़े पहनता हूँ।', 'I get dressed quickly.', 2, 'kapde pehenna'),
        ('दाँत साफ़ करना', "to brush one's teeth", 'phrase',
         'मैं दाँत साफ़ करता हूँ।', 'I brush my teeth.', 2, 'daant saaf karna'),
        ('काम', 'work, job', 'noun',
         'मैं बस से काम पर जाता हूँ।', 'I go to work by bus.', 1, 'kaam'),
        ('दोपहर का खाना', 'lunch', 'noun',
         'मैं एक बजे दोपहर का खाना खाता हूँ।', 'I have lunch at one.', 1,
         'dopahar ka khaana'),
        ('रात का खाना', 'dinner', 'noun',
         'हम आठ बजे रात का खाना खाते हैं।', 'We have dinner at eight.', 1,
         'raat ka khaana'),
        ('सोना', 'to sleep, to go to bed', 'verb',
         'मैं ग्यारह बजे सोता हूँ।', 'I go to bed at eleven.', 2, 'sona'),
        ('सुबह', 'morning', 'noun',
         'सुबह मैं पढ़ता हूँ।', 'In the morning I read.', 1, 'subah'),
        ('दोपहर', 'afternoon', 'noun',
         'मैं दोपहर में पढ़ाई करता हूँ।', 'I study in the afternoon.', 1, 'dopahar'),
        ('रात', 'night', 'noun',
         'मैं रात में काम करता हूँ।', 'I work at night.', 1, 'raat'),
        ('जल्दी', 'early, quickly', 'adverb',
         'मैं बहुत जल्दी उठता हूँ।', 'I get up very early.', 1, 'jaldi'),
        ('देर से', 'late', 'adverb',
         'मैं काम पर देर से पहुँचता हूँ।', 'I arrive late to work.', 2, 'der se'),
        ('हमेशा', 'always', 'adverb',
         'मैं हमेशा घर पर नाश्ता करता हूँ।', 'I always have breakfast at home.', 1,
         'hamesha'),
        ('कभी-कभी', 'sometimes', 'adverb',
         'कभी-कभी मैं सुबह दौड़ता हूँ।', 'Sometimes I run in the morning.', 2,
         'kabhi-kabhi'),
        ('से पहले', 'before', 'postposition',
         'सोने से पहले मैं किताब पढ़ता हूँ।', 'Before sleeping I read a book.', 2,
         'se pehle'),
        ('के बाद', 'after', 'postposition',
         'खाने के बाद मैं टीवी देखता हूँ।', 'After eating I watch TV.', 2, 'ke baad'),
        ('आराम करना', 'to rest', 'phrase',
         'मैं रविवार को आराम करता हूँ।', 'I rest on Sunday.', 1, 'aaraam karna'),
    ],
    ORDERING_FOOD: [
        ('मेज़', 'table', 'noun',
         'दो लोगों के लिए एक मेज़, कृपया।', 'A table for two, please.', 1, 'mez'),
        ('मेन्यू', 'menu', 'noun',
         'क्या आप मेन्यू ला सकते हैं?', 'Could you bring the menu?', 1, 'menyu'),
        ('वेटर', 'waiter', 'noun',
         'वेटर बहुत अच्छा है।', 'The waiter is very kind.', 1, 'vetar'),
        ('ऑर्डर करना', 'to order', 'phrase',
         'मैं बिरयानी ऑर्डर करना चाहता हूँ।', 'I want to order the biryani.', 2,
         'order karna'),
        ('बिल', 'the bill, the check', 'noun',
         'बिल लाइए, कृपया।', 'The bill, please.', 1, 'bil'),
        ('पानी', 'water', 'noun',
         'एक गिलास पानी, कृपया।', 'A glass of water, please.', 1, 'paani'),
        ('चाय', 'tea', 'noun',
         'एक कप चाय, कृपया।', 'A cup of tea, please.', 1, 'chaay'),
        ('रोटी', 'bread', 'noun',
         'क्या आप और रोटी ला सकते हैं?', 'Could you bring more bread?', 1, 'roti'),
        ('खाना', 'food, dish', 'noun',
         'यह खाना बहुत स्वादिष्ट है।', 'This dish is delicious.', 1, 'khaana'),
        ('पीना', 'to drink', 'verb',
         'आप क्या पीना चाहेंगे?', 'What would you like to drink?', 1, 'peena'),
        ('मिठाई', 'dessert, sweet', 'noun',
         'मिठाई में गुलाब जामुन।', 'Gulab jamun for dessert.', 2, 'mithaai'),
        ('सलाद', 'salad', 'noun',
         'एक सलाद, कृपया।', 'A salad, please.', 1, 'salaad'),
        ('मुर्गा', 'chicken', 'noun',
         'चावल के साथ मुर्गा।', 'Chicken with rice.', 1, 'murga'),
        ('माँस', 'meat', 'noun',
         'मैं माँस नहीं खाता।', "I don't eat meat.", 1, 'maans'),
        ('मछली', 'fish', 'noun',
         'मछली बहुत ताज़ी है।', 'The fish is very fresh.', 1, 'machhli'),
        ('तीखा', 'spicy', 'adjective',
         'क्या यह बहुत तीखा है?', 'Is it very spicy?', 2, 'teekha'),
        ('पैक करके', 'to take away', 'phrase',
         'यह पैक करके दीजिए।', 'Please pack it to take away.', 2, 'pack karke'),
        ('मुझे चाहिए', 'I would like', 'phrase',
         'मुझे एक कॉफ़ी चाहिए।', 'I would like a coffee.', 2, 'mujhe chaahiye'),
        ('कितने का है', 'how much does it cost', 'phrase',
         'यह खाना कितने का है?', 'How much is this dish?', 2, 'kitne ka hai'),
        ('मुझे एलर्जी है', "I'm allergic", 'phrase',
         'मुझे मूँगफली से एलर्जी है।', "I'm allergic to peanuts.", 3,
         'mujhe allergy hai'),
    ],
    TRAVEL_BASICS: [
        ('हवाई अड्डा', 'airport', 'noun',
         'मैं टैक्सी से हवाई अड्डे जाता हूँ।', "I'm going to the airport by taxi.", 1,
         'hawaai adda'),
        ('टिकट', 'ticket', 'noun',
         'दिल्ली के लिए एक टिकट, कृपया।', 'A ticket to Delhi, please.', 1, 'tikat'),
        ('स्टेशन', 'station', 'noun',
         'स्टेशन पास में है।', 'The station is close by.', 1, 'station'),
        ('ट्रेन', 'train', 'noun',
         'ट्रेन नौ बजे जाती है।', 'The train leaves at nine.', 1, 'train'),
        ('बस', 'bus', 'noun',
         'मैं शहर के लिए बस लेता हूँ।', 'I take the bus downtown.', 1, 'bas'),
        ('होटल', 'hotel', 'noun',
         'होटल शहर के बीच में है।', 'The hotel is downtown.', 1, 'hotal'),
        ('कमरा', 'room', 'noun',
         'एक डबल कमरा, कृपया।', 'A double room, please.', 2, 'kamra'),
        ('सूटकेस', 'suitcase', 'noun',
         'मेरा सूटकेस नीला है।', 'My suitcase is blue.', 1, 'suitcase'),
        ('पासपोर्ट', 'passport', 'noun',
         'यह मेरा पासपोर्ट है।', 'Here is my passport.', 1, 'paasport'),
        ('कहाँ है', 'where is', 'phrase',
         'बाथरूम कहाँ है?', 'Where is the bathroom?', 1, 'kahaan hai'),
        ('दाएँ', 'to the right', 'adverb',
         'दाएँ मुड़िए।', 'Turn right.', 2, 'daaen'),
        ('बाएँ', 'to the left', 'adverb',
         'संग्रहालय बाएँ है।', 'The museum is on the left.', 2, 'baaen'),
        ('पास', 'near', 'adverb',
         'समुद्र तट पास है।', 'The beach is near.', 1, 'paas'),
        ('दूर', 'far', 'adverb',
         'हवाई अड्डा दूर है।', 'The airport is far.', 1, 'door'),
        ('रास्ता भूलना', 'to be lost', 'phrase',
         'मैं रास्ता भूल गया हूँ।', "I'm lost.", 2, 'raasta bhoolna'),
        ('नक्शा', 'map', 'noun',
         'क्या आपके पास शहर का नक्शा है?', 'Do you have a map of the city?', 1,
         'naksha'),
        ('बुक करना', 'to book, to reserve', 'phrase',
         'मैं एक कमरा बुक करना चाहता हूँ।', 'I want to book a room.', 2,
         'book karna'),
        ('उड़ान', 'flight', 'noun',
         'मेरी उड़ान देर से है।', 'My flight is delayed.', 2, 'udaan'),
        ('कितने बजे जाती है', 'what time does it leave', 'phrase',
         'ट्रेन कितने बजे जाती है?', 'What time does the train leave?', 2,
         'kitne baje jaati hai'),
        ('मदद', 'help', 'noun',
         'मुझे मदद चाहिए, कृपया।', 'I need help, please.', 1, 'madad'),
    ],
}


VOCAB = {
    'Spanish': SPANISH_VOCAB,
    'French': FRENCH_VOCAB,
    'German': GERMAN_VOCAB,
    'Hindi': HINDI_VOCAB,
}


class Command(BaseCommand):
    help = 'Seed the three topics with vocabulary and create the demo learner.'

    def add_arguments(self, parser):
        parser.add_argument(
            '--reset',
            action='store_true',
            help='Delete existing vocab, scheduling state and sessions first.',
        )

    @transaction.atomic
    def handle(self, *args, **options):
        if options['reset']:
            session_count = ConversationSession.objects.count()
            state_count = UserVocabState.objects.count()
            vocab_count = VocabItem.objects.count()
            ConversationSession.objects.all().delete()
            UserVocabState.objects.all().delete()
            VocabItem.objects.all().delete()
            self.stdout.write(self.style.WARNING(
                f'--reset: removed {vocab_count} vocab items, '
                f'{state_count} scheduling states, {session_count} sessions.'
            ))

        created_total = updated_total = 0
        topic_labels = dict(VocabItem._meta.get_field('topic').choices)

        for language, topics in VOCAB.items():
            self.stdout.write(self.style.MIGRATE_HEADING(language))
            for topic, entries in topics.items():
                created = updated = 0
                for entry in entries:
                    term, english, pos, example, example_en, difficulty = entry[:6]
                    # Only the non-Latin languages carry a seventh value.
                    romanisation = entry[6] if len(entry) > 6 else ''
                    _item, was_created = VocabItem.objects.update_or_create(
                        language=language,
                        topic=topic,
                        term=term,
                        defaults={
                            'english': english,
                            'part_of_speech': pos,
                            'example': example,
                            'example_en': example_en,
                            'difficulty': difficulty,
                            'romanisation': romanisation,
                        },
                    )
                    if was_created:
                        created += 1
                    else:
                        updated += 1
                created_total += created
                updated_total += updated
                self.stdout.write(
                    f'  {topic_labels[topic]:<16} {created:>2} created, '
                    f'{updated:>2} updated ({len(entries)} total)'
                )

        demo_user, user_created = User.objects.get_or_create(
            username=settings.DEMO_USERNAME,
            defaults={'first_name': 'Demo', 'last_name': 'Learner'},
        )
        if user_created:
            # The demo learner is never logged into, so give it no usable
            # password rather than inventing a credential.
            demo_user.set_unusable_password()
            demo_user.save(update_fields=['password'])

        self.stdout.write('')
        self.stdout.write(self.style.SUCCESS(
            f'Seeded {VocabItem.objects.count()} vocab items across '
            f'{len(VOCAB)} languages '
            f'({created_total} created, {updated_total} updated).'
        ))
        self.stdout.write(
            f'Demo learner "{demo_user.username}": '
            f'{"created" if user_created else "already existed"}.'
        )
